kind: List
items:
  - apiVersion: "v1"
    kind: "Pod"
    metadata:
      generateName: ember-csi-1-
      labels:
        app: ember-csi
        env: test
    spec:
      containers:
        - name: ember-csi
          image: quay.io/pod_utils/systemd-libvirt-centos-vm:latest
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
              - test
              - -e
              - /var/tmp/vagrant-vm-up
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 50
