# Pin kubernetes version to ensure we don't break every other day
# Disabling CoreDNS to workaround https://github.com/kubernetes/kubeadm/issues/998
- name: initialize kubeadm on master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --token={{ kubernetes_token }} --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}

- name: create flannel network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.11.0/Documentation/kube-flannel.yml

- name: get kubeconfig.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: kubeconfig.conf
    flat: yes

- file: path=/home/vagrant/.kube state=directory group=vagrant owner=vagrant
- name: Set default vagrant kubeconf
  copy:
    remote_src: True
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    group: vagrant
    owner: vagrant

- file: path=/root/.kube state=directory
- name: Set default root kubeconf
  copy:
    remote_src: True
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config

- import_tasks: setup_lvm.yml
  become: yes

- name: Copy sysfiles tar and deploy secret
  import_tasks: setup_sysfiles.yml
